version: "3.7"

services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    networks:
      - nacos_custom_network

  prometheus:
    container_name: nacos-prometheus-49090
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "49090:9090"
    depends_on:
      - nacos
    restart: on-failure
    networks:
      - nacos_custom_network

  grafana:
    container_name: nacos-grafana-43000
    image: grafana/grafana:latest
    ports:
      - 43000:3000
    restart: on-failure
    networks:
      - nacos_custom_network

networks:
  nacos_custom_network:
    driver: bridge
    name: nacos_custom_network
